import { runRules } from "@/lib/detectors/batch";
import {
  mockAnomalies,
  mockAnomalyExplanations,
  mockInvoiceExceptions,
  mockInvoiceLines,
  mockInvoices,
  mockPayments,
  mockPurchaseOrders,
  mockSuppliers,
} from "@/lib/fixtures";
import type {
  Anomaly,
  AnomalyDetail,
  AnomalyExplanation,
  AnomalyListItem,
  AnomalyStatus,
} from "@/lib/schemas";
import type { AnomalyFilters, DataSource } from "@/lib/types/dashboard";

/**
 * Data seam for Page 2 (PLAN-07). Shapes are the shared contract in lib/schemas/api.ts.
 * TODO(feat/ingestion-api): once `npm run anomalies:batch -- --source db --persist` has populated
 * Postgres, switch to Drizzle queries on `anomalies` joined to `invoices`, `suppliers` and
 * `anomaly_explanations` (lib/db) and set anomaliesSource = "live".
 * Explanations are generated by lib/explanations (Bedrock); this file only stores them.
 */
export const anomaliesSource: DataSource = "mock";

/** Matches the as-of date used by the detector CI run, so overdue findings are reproducible. */
export const FIXTURE_AS_OF = "2026-10-08";

// Mock mode runs the real PLAN-03 rule detectors over the fixture rows, plus the fixture's
// statistical/Isolation Forest examples (no ML service needed). Cloned so status changes stay local.
const ruleAnomalies: Anomaly[] = runRules(
  {
    invoices: mockInvoices,
    invoiceLines: mockInvoiceLines,
    purchaseOrders: mockPurchaseOrders,
    payments: mockPayments,
    invoiceExceptions: mockInvoiceExceptions,
  },
  FIXTURE_AS_OF,
).map((a, i) => ({
  ...a,
  // Deterministic IDs/timestamps keep server renders stable (no randomness under Cache Components).
  anomaly_id: `00000000-0000-4000-8000-${String(i + 1).padStart(12, "0")}`,
  status: "Needs review",
  created_at: `${FIXTURE_AS_OF} 02:00:00+00`,
}));
const modelAnomalies = structuredClone(mockAnomalies.filter((a) => a.method !== "rule"));

const anomalies: Anomaly[] = [...ruleAnomalies, ...modelAnomalies];
const explanations: AnomalyExplanation[] = structuredClone(
  mockAnomalyExplanations.filter((e) => modelAnomalies.some((a) => a.anomaly_id === e.anomaly_id)),
);

function invoiceFor(a: Anomaly) {
  return mockInvoices.find((i) => i.invoice_id === a.invoice_id) ?? null;
}

function toListItem(a: Anomaly): AnomalyListItem | null {
  const invoice = invoiceFor(a);
  const supplier = invoice && mockSuppliers.find((s) => s.supplier_id === invoice.supplier_id);
  if (!invoice || !supplier) return null;
  return {
    ...a,
    invoice_number: invoice.invoice_number,
    invoice_date: invoice.invoice_date,
    amount_usd: invoice.amount_usd,
    supplier_id: supplier.supplier_id,
    supplier_name: supplier.supplier_name,
    has_explanation: explanations.some((e) => e.anomaly_id === a.anomaly_id),
  };
}

export async function listAnomalies(filters: AnomalyFilters = {}): Promise<AnomalyListItem[]> {
  const q = filters.q?.trim().toLowerCase();
  return anomalies
    .map(toListItem)
    .filter((a): a is AnomalyListItem => a !== null)
    .filter(
      (a) =>
        (!q ||
          [a.invoice_id, a.invoice_number, a.supplier_name, a.category].some((v) => v.toLowerCase().includes(q))) &&
        (!filters.category || a.category === filters.category) &&
        (!filters.priority || a.priority === filters.priority) &&
        (!filters.status || a.status === filters.status) &&
        (!filters.supplier_id || a.supplier_id === filters.supplier_id) &&
        (!filters.from || a.invoice_date >= filters.from) &&
        (!filters.to || a.invoice_date <= filters.to),
    )
    .sort((a, b) => b.invoice_date.localeCompare(a.invoice_date));
}

export async function getAnomalyDetail(anomalyId: string): Promise<AnomalyDetail | null> {
  const anomaly = anomalies.find((a) => a.anomaly_id === anomalyId);
  const invoice = anomaly && invoiceFor(anomaly);
  const supplier = invoice && mockSuppliers.find((s) => s.supplier_id === invoice.supplier_id);
  if (!anomaly || !invoice || !supplier) return null;
  return {
    anomaly,
    invoice,
    supplier,
    explanation: explanations.find((e) => e.anomaly_id === anomalyId) ?? null,
  };
}

export async function updateAnomalyStatus(anomalyId: string, status: AnomalyStatus): Promise<AnomalyDetail | null> {
  const anomaly = anomalies.find((a) => a.anomaly_id === anomalyId);
  if (!anomaly) return null;
  anomaly.status = status;
  return getAnomalyDetail(anomalyId);
}

export async function getAnomalyRow(anomalyId: string): Promise<Anomaly | null> {
  return anomalies.find((a) => a.anomaly_id === anomalyId) ?? null;
}

export async function getExplanationRow(anomalyId: string): Promise<AnomalyExplanation | null> {
  return explanations.find((e) => e.anomaly_id === anomalyId) ?? null;
}

export async function saveExplanationRow(row: AnomalyExplanation): Promise<AnomalyExplanation> {
  const i = explanations.findIndex((e) => e.anomaly_id === row.anomaly_id);
  if (i >= 0) explanations[i] = row;
  else explanations.push(row);
  return row;
}
