/**
 * Zod schemas for the app-native `anomalies` and `anomaly_explanations`
 * tables.
 *
 * ## `anomalies.evidence` (freeform jsonb)
 *
 * Evidence is intentionally NOT a rigid schema — its shape differs per
 * category and will evolve as `feat/anomaly-rules` and
 * `feat/anomaly-engine-ml` land. It must only contain verified facts/numbers
 * (the AI explanation layer may only cite values present here). Keys are
 * camelCase. Expected keys by category (amounts are USD unless the key says
 * otherwise):
 *
 * All categories (recommended):
 *   - `summary`: string — one-line human-readable evidence for table views
 *   - `groundTruthExceptionIds`: string[] — matching `invoice_exceptions` rows, if any
 *
 * `Duplicate invoice` (rule):
 *   - `matchedInvoiceId`, `invoiceNumber`, `matchedInvoiceNumber`
 *   - `amountUsd`, `matchedAmountUsd`, `daysApart`
 *   - `matchType`: 'exact_number' | 'near_number' | 'same_amount'
 * `Missing PO` (rule):
 *   - `amountUsd`, `approvalLevel`
 * `Price/quantity mismatch` (rule):
 *   - `poId`, `currency`, `poAmount`, `invoiceLinesTotal`, `difference`, `differencePct`
 * `Tax/total error` (rule):
 *   - `currency`, `netAmount`, `taxAmount`, `grossAmount`, `expectedGrossAmount`,
 *     `difference`, `tolerance`, optional `invoiceLinesTotal`
 * `Overdue invoice` (rule):
 *   - unpaid: `dueDate`, `asOfDate`, `daysOverdue`, `invoiceStatus`
 *   - paid late: `dueDate`, `paidAt`, `daysVsDue`
 * `Unusual vendor transaction` (rule):
 *   - `amountUsd`, `vendorAvgUsd`, `ratio`, `threshold`, `vendorInvoiceCount`
 * `Unusually high amount` (statistical):
 *   - `amountUsd`, `comparisonGroup` (e.g. 'supplier:SUP000001', 'category:Software'),
 *     `groupMeanUsd`, `groupStdUsd`, `zScore`, `threshold`
 * `Unexpected payment timing` (statistical):
 *   - `metric` ('processing_days' | 'days_vs_due'), `value`, `comparisonGroup`,
 *     `groupMean`, `groupStd`, `zScore`, `threshold`
 * `Multivariate outlier` (isolation_forest):
 *   - `threshold`, `modelVersion`, `features` (object of the feature values scored,
 *     e.g. `amountUsd`, `vendorAvgUsd`, `processingDays`, `ocrConfidence`,
 *     `supplierExceptionRate`)
 */
import { z } from "zod";

import { idSchema, timestampSchema } from "./common";
import {
  ANOMALY_METHODS,
  ANOMALY_PRIORITIES,
  ANOMALY_STATUSES,
} from "./enums";

export const anomalyMethodSchema = z.enum(ANOMALY_METHODS);
export const anomalyPrioritySchema = z.enum(ANOMALY_PRIORITIES);
export const anomalyStatusSchema = z.enum(ANOMALY_STATUSES);

/** Freeform per-category facts; see the module comment for expected keys. */
export const anomalyEvidenceSchema = z.record(z.string(), z.unknown());
export type AnomalyEvidence = z.infer<typeof anomalyEvidenceSchema>;

export const anomalySchema = z.object({
  anomaly_id: z.uuid(),
  invoice_id: idSchema,
  /** Which detector layer produced this anomaly. */
  method: anomalyMethodSchema,
  /** Anomaly type; prefer `KNOWN_ANOMALY_CATEGORIES` values. */
  category: z.string().min(1),
  priority: anomalyPrioritySchema,
  /**
   * Method-specific score: null for `rule`, |z-score| for `statistical`, raw
   * Isolation Forest score for `isolation_forest` (see `evidence.threshold`).
   * Never generated by the LLM.
   */
  score: z.number().nullable(),
  evidence: anomalyEvidenceSchema,
  /** Human review state. Detectors insert `Needs review`; only people change it. */
  status: anomalyStatusSchema,
  created_at: timestampSchema,
});
export type Anomaly = z.infer<typeof anomalySchema>;

/** Payload detectors use to insert/upsert an anomaly (id/timestamps are DB-generated). */
export const newAnomalySchema = anomalySchema
  .omit({ anomaly_id: true, created_at: true, status: true })
  .extend({ status: anomalyStatusSchema.optional() });
export type NewAnomaly = z.infer<typeof newAnomalySchema>;

/** Request body for changing an anomaly's review status. */
export const updateAnomalyStatusSchema = z.object({
  status: anomalyStatusSchema,
});
export type UpdateAnomalyStatus = z.infer<typeof updateAnomalyStatusSchema>;

/**
 * Bedrock-generated explanation of an anomaly (`feat/ai-explanations`).
 * Must only reference facts present in the anomaly's `evidence`.
 */
export const anomalyExplanationSchema = z.object({
  anomaly_id: z.uuid(),
  /** Plain-language description of what looks unusual and why. */
  explanation: z.string(),
  /** Short restatement of the evidence values the explanation relies on. */
  evidence_summary: z.string(),
  /** Possible business/financial impact if left unaddressed. */
  potential_impact: z.string(),
  /** Ordered next steps for the human reviewer (recommendations, never auto-actions). */
  recommended_actions: z.array(z.string()),
  /** Process/control change that would prevent recurrence. */
  preventive_measure: z.string(),
  /** Always true for supplier-risk or payment decisions (hackathon human-in-the-loop rule). */
  requires_human_review: z.boolean(),
  /** Bedrock model ID used, stored for AI-usage disclosure. */
  model_id: z.string().min(1),
  generated_at: timestampSchema,
});
export type AnomalyExplanation = z.infer<typeof anomalyExplanationSchema>;

/** Payload for inserting an explanation (`generated_at` defaults to now). */
export const newAnomalyExplanationSchema = anomalyExplanationSchema
  .omit({ generated_at: true, requires_human_review: true })
  .extend({ requires_human_review: z.boolean().optional() });
export type NewAnomalyExplanation = z.infer<typeof newAnomalyExplanationSchema>;
